// src/lib/use-bootstrap-tag.tsx
/* eslint-disable no-new-func */
import { effect, state } from './reactive'
import { arraysAreEqual, change, createElement, processData, pull } from './util'

const name = 'use-bootstrap-tag'
const classTarget = `${name}-target`

export default function UseBootstrapTag(element: Element | HTMLElement | null) {
  const target = element as HTMLInputElement

  // If reinitialized
  const nextElement = target.nextElementSibling
  if (nextElement && nextElement.classList.contains(name)) {
    nextElement.remove()
  }

  // Root
  const root = createElement('div')
  target.insertAdjacentElement('afterend', root)

  // Config
  const dataset = target.dataset
  const config = {
    separator: dataset.ubTagSeparator || ',',
    variant: dataset.ubTagVariant || 'secondary',
    xPosition: dataset.ubTagXPosition as 'left' | 'right' || 'right',
    transform: dataset.ubTagTransform || 'input => input',
    isDuplicate: dataset.ubTagDuplicate !== undefined,
    max: +dataset.ubTagMax! > 0 ? +dataset.ubTagMax! : undefined,
    noInputOnblur: dataset.ubTagNoInputOnblur !== undefined,
  }

  const tags = () => root.querySelectorAll('button')
  const animateTag = (tag: HTMLButtonElement) => {
    tag.classList.add('duplicate')
    setTimeout(() => {
      tag.classList.remove('duplicate')
    }, 150)
  }

  // Returned methods
  const getValue = (): string => target.value
  const getValues = (): string[] => getValue().split(config.separator).filter(i => i !== '')
  const addValue = (value: string | string[]): void => {
    const values = getValues()
    const insert = processData(value, config.separator)
    if (!config.max || values.length < config.max) {
      // Get duplicates
      const duplicates = [] as number[]
      !config.isDuplicate && values.forEach((value, index) => insert.includes(value) && duplicates.push(index))

      // Get inserted
      const inserted = [] as string[]
      insert.forEach((i) => {
        if (values.includes(i)) {
          config.isDuplicate && inserted.push(i)
        }
        else {
          inserted.push(i)
        }
      })

      values.push(...inserted)
      if (!arraysAreEqual(getValues(), values)) {
        change(target, values.join(config.separator))
        // Animate inserts
        inserted.forEach((item) => {
          const tag = tags()[values.lastIndexOf(item)]
          const tagHeight = tag.offsetHeight
          tag!.style.height = 0 as unknown as string
          setTimeout(() => (tag.style.height = `${tagHeight}px`), 0)
          setTimeout(() => tag.style.removeProperty('height'), 150)
        })
      }
      // Animate duplicates
      if (!config.isDuplicate) {
        duplicates.forEach(index => animateTag(tags()[index]))
      }
    }
    else {
      insert.length > 0 && tags().forEach(animateTag)
    }
  }
  const removeValue = (value: string | string[]): void => {
    const values = getValues()
    const remove = processData(value, config.separator)
    remove.forEach(i => pull(values, i))
    if (!arraysAreEqual(getValues(), values)) {
      change(target, values.join(config.separator))
    }
  }

  // Target states
  const classList = target.classList
  const disabled = target.disabled

  target.tabIndex = -1
  classList.add(classTarget)

  // Local states
  const [value, setValue] = state(target.value)
  const [focus, setFocus] = state(false)
  const [text, setText] = state('')
  const values = () => value().split(config.separator).filter(i => i.trim() !== '')
  const texts = () => Function(`return ${config.transform}`)()(text().trim()) as string
  const placeholder = () => values().length ? '' : target.placeholder

  // Styling
  root.className = `${name} d-flex flex-wrap align-items-center gap-1 ${classList.value}`.replace(classTarget, '')
  effect(() => {
    focus() ? root.classList.add('focus') : root.classList.remove('focus')
  })

  // Functions
  const textFocus = () => root.querySelector('input')?.focus()
  const removeByIndex = (index: number) => {
    if (index >= 0) {
      removeValue(values()[index])
    }
  }
  const appendTag = (force = false) => {
    const value = texts()
    value === '' && setText('')
    if (text().includes(config.separator) || (force && text() !== '')) {
      addValue(value.split(config.separator).filter(i => i.trim() !== ''))
      setText('')
    }
  }

  // Tags
  const tagElement = createElement('button', {
    type: 'button',
    className: `align-items-center gap-1 d-inline-flex py-0 border-0 btn btn-${config.variant}`,
    disabled,
  })
  classList.contains('form-control-sm') && tagElement.classList.add('btn-sm')
  classList.contains('form-control-lg') && tagElement.classList.add('btn-lg')
  config.xPosition === 'left' && tagElement.classList.add('flex-row-reverse')
  const closeTagElement = createElement('span', {
    className: 'd-inline-flex',
    role: 'button',
    tabIndex: -1,
    innerHTML: '<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" /></svg>',
  })
  const renderTags = (items: string[]) => {
    tags().forEach(tag => tag.remove())
    items.reverse().forEach((value, i) => {
      const index = items.length - 1 - i
      const tag = tagElement.cloneNode() as typeof tagElement
      tag.innerHTML = value
      tag.onfocus = () => {
        tag.classList.add('active')
        setFocus(true)
      }
      tag.onblur = () => {
        tag.classList.remove('active')
        setFocus(false)
      }
      tag.onkeydown = ({ key }) => {
        if (key === 'Backspace' || key === 'Delete') {
          removeByIndex(index)
          const nextFocus = key === 'Backspace' ? index - 1 : values().length === index ? -1 : index
          if (nextFocus === -1) {
            textFocus()
          }
          else {
            tags()[nextFocus].focus()
          }
        }
      }
      if (!disabled) {
        const span = closeTagElement.cloneNode(true) as typeof closeTagElement
        span.onclick = () => {
          removeByIndex(index)
          textFocus()
        }
        tag.append(span)
      }
      root.prepend(tag)
    })
  }
  effect(() => {
    renderTags(values())
  })

  // Input
  if (!disabled) {
    const wrapper = createElement('div', {
      className: 'input-wrapper',
    })
    const span = createElement('span')
    const input = createElement('input', {
      type: 'text',
    })
    input.onfocus = () => {
      setFocus(true)
    }
    input.onblur = () => {
      setFocus(false)
      config.noInputOnblur ? setText('') : appendTag(true)
    }
    input.onkeydown = (e) => {
      if (text() === '' && e.key === 'Backspace') {
        removeByIndex(values().length - 1)
      }
      if (text() !== '' && e.key === 'Enter') {
        appendTag(true)
        e.preventDefault() // prevent form submit
      }
    }
    input.oninput = () => {
      setText(input.value)
      appendTag()
    }
    effect(() => {
      span.innerHTML = text() || placeholder() || 'i'
      input.placeholder = placeholder()
      input.value = text()
    })
    wrapper.append(span, input)
    root.append(wrapper)
  }

  root.onclick = (e) => {
    if ((e.target as Element).tagName !== 'BUTTON') {
      textFocus()
    }
  }

  target.addEventListener('change', () => {
    setValue(target.value)
  })
  target.addEventListener('focus', textFocus)

  return { getValue, getValues, addValue, removeValue }
}

// src/lib/use-bootstrap-tag.svelte
<script lang="ts">
  import { onMount, tick } from 'svelte'
  import { slide } from 'svelte/transition'
  import {
    change,
    classCenterGap,
    classInlineFlex,
    keyBackspace,
    shake,
    type Options,
  } from './util'

  export let inputElement: HTMLInputElement
  export let options: Options

  const name = 'use-bootstrap-tag'
  const disabled = inputElement.disabled
  const sm = inputElement.classList.contains('form-control-sm')
  const lg = inputElement.classList.contains('form-control-lg')
  const left = options.xPosition === 'left'

  let root: HTMLDivElement
  let value = ''
  let focus = false
  let valid = false
  let invalid = false
  let text = ''
  let textElement: HTMLInputElement | undefined
  let textWidth = 0
  let textFocus = false
  let tagActiveIndex = -1

  $: values = value.split(options.separator).filter((i) => i !== '')
  $: if (textElement) {
    const canvas = document.createElement('canvas')
    const context = canvas.getContext('2d')
    if (context) {
      context.font = getComputedStyle(textElement).font
      textWidth = context.measureText(
        text || textElement.placeholder || ''
      ).width
    }
    canvas.remove()
  }
  $: if (textFocus) {
    textElement.focus()
  }

  inputElement.classList.add(`${name}-target`)
  inputElement.tabIndex = -1

  onMount(() => {
    setValueFromInputElement()
    inputElement.addEventListener('change', setValueFromInputElement)
    inputElement.addEventListener('focus', () => (textFocus = true))
    if (inputElement.form) {
      handleValidation()
    }
  })

  function setValueFromInputElement() {
    value = inputElement.value
  }
  function toggleValidationClasses() {
    valid = false
    invalid = false
    if (inputElement.form.classList.contains('was-validated')) {
      if (inputElement.validity.valid) {
        valid = true
      } else {
        invalid = true
      }
    }
  }
  function handleValidation() {
    toggleValidationClasses()
    const observer = new MutationObserver((mutations) => {
      mutations.forEach((mutation) => {
        if (mutation.attributeName === 'class') {
          toggleValidationClasses()
        }
      })
    })
    observer.observe(inputElement.form, {
      attributes: true,
      attributeFilter: ['class'],
    })
  }
  function handleRootClick(e: MouseEvent) {
    if ((e.target as HTMLElement).tagName.toLowerCase() !== 'button') {
      textFocus = true
    }
  }
  function handleTagFocus(e: FocusEvent) {
    const tag = e.target as HTMLButtonElement
    focus = true
    tag.classList.add('active')
    tagActiveIndex = +tag.dataset.index
  }
  function handleTagBlur(e: FocusEvent) {
    const tag = e.target as HTMLButtonElement
    focus = false
    tag.classList.remove('active')
    tagActiveIndex = -1
  }
  function setValues(values: string[]) {
    change(inputElement, values.join(options.separator))
    if (inputElement.form) {
      toggleValidationClasses()
    }
  }
  function handleRemove(index: number) {
    if (index >= 0) {
      setValues(values.filter((_, i) => i !== index))
    }
  }
  async function handleTagKeyup(e: KeyboardEvent) {
    if (e.key === keyBackspace || e.key === 'Delete') {
      handleRemove(+(e.target as HTMLButtonElement).dataset.index)
      await tick()
      if (tagActiveIndex === -1) {
        textFocus = true
      }
    }
  }
  function handleExists(existingIndex: number[]) {
    existingIndex.forEach((index) => {
      const tag = root.querySelector<HTMLButtonElement>(
        `button:nth-child(${index + 1})`
      )
      if (tag) {
        tag.style.transform = 'scale(1.1)'
        setTimeout(() => {
          tag.style.transform = 'none'
        }, 150)
      }
    })
  }
  function appendTag(force = false) {
    const value = Function(`return ${options.transform}`)()(
      text.trim()
    ) as string
    if (value === '') {
      text = ''
    }
    if (text.includes(options.separator) || (force && text !== '')) {
      let newValues = value
        .split(options.separator)
        .filter((i) => i.trim() !== '')
      if (newValues.length > 0) {
        if (!options.isDuplicate) {
          const existingIndex: number[] = []
          values.forEach((currentValue, index) => {
            if (newValues.includes(currentValue)) {
              existingIndex.push(index)
            }
          })
          newValues = shake(newValues, values)
          handleExists(existingIndex)
        }
        values.push(...newValues)
        setValues(values)
      }
      text = ''
    }
  }
  function handleTextElementBlur() {
    focus = false
    appendTag(true)
    textFocus = false
  }
  function handleTextElementKeydown(e: KeyboardEvent) {
    if (text === '' && e.key === keyBackspace) {
      handleRemove(values.length - 1)
    }
    if (options.isEnter && text !== '' && e.key === 'Enter') {
      appendTag(true)
      e.preventDefault() // prevent form submit
    }
  }
</script>

<div
  bind:this={root}
  class={`${name} d-flex flex-wrap ${classCenterGap} ${inputElement.classList.value}`}
  class:disabled
  class:focus
  class:is-valid={valid}
  class:is-invalid={invalid}
  on:click={handleRootClick}
  on:keydown={undefined}
  role="none"
>
  {#each values as value, index}
    <button
      type="button"
      class={`${classCenterGap} ${classInlineFlex} py-0 border-0 btn btn-${options.variant}`}
      class:flex-row-reverse={left}
      class:btn-sm={sm}
      class:btn-lg={lg}
      {disabled}
      data-index={index}
      on:focus={handleTagFocus}
      on:blur={handleTagBlur}
      on:keyup={handleTagKeyup}
      in:slide={{ duration: 150 }}
    >
      {value}
      {#if !disabled}
        <span
          class={classInlineFlex}
          role="button"
          tabindex="-1"
          on:click={() => handleRemove(index)}
          on:keydown={undefined}
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="1em"
            height="1em"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <line x1="18" y1="6" x2="6" y2="18" />
            <line x1="6" y1="6" x2="18" y2="18" />
          </svg>
        </span>
      {/if}
    </button>
  {/each}
  <input
    type="text"
    placeholder={inputElement.placeholder}
    bind:this={textElement}
    bind:value={text}
    style:width={`${textWidth}px`}
    {disabled}
    on:focus={() => (focus = true)}
    on:blur={handleTextElementBlur}
    on:keydown={handleTextElementKeydown}
    on:input={() => appendTag()}
  />
</div>
